schema_version: 1

context:
  name: azure-keyvault-administration
  version: 4.4.0b2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-keyvault-administration-${{ version }}.tar.gz
  sha256: 8d0edefad78024c3a97b071fa5cf50daf923085e9d4379259f7237d911e66810

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-core >=1.24.0,<2.0
    - isodate >=0.6.1
    - typing_extensions >=4.0.1

tests:
  - python:
      imports:
        - azure.keyvault.administration
        - azure.keyvault.administration._generated
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Key Vault Administration Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault-administration

extra:
  recipe-maintainers:
    - janjagusch
