schema_version: 1

context:
  name: azure-keyvault-administration
  version: "4.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_keyvault_administration-${{ version }}.tar.gz
  sha256: d583029e2efaa09e1e1c46f7c01bb1bc1f890388acbf2354a42d1f3379f734e4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-core >=1.31.0
    - isodate >=0.6.1
    - typing_extensions >=4.6.0

tests:
  - python:
      imports:
        - azure.keyvault.administration
        - azure.keyvault.administration._generated
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Key Vault Administration Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault-administration

extra:
  recipe-maintainers:
    - janjagusch
